services:
  - type: web
    name: task-panel
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
